config/routes.rb
Blog::Application.routes.draw do

  get "sitemap/index"

  devise_for :users, {controllers: {omniauth_callbacks: "omniauth_callbacks"}}

  root to: "articles#index"

  resources :users, only: [:show, :index, :update]

  resources :articles, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :tags, only: [:show]

  namespace :admin do
    resources :articles do
      resources :article_images, only: [:create, :update, :destroy]
      get :drafts, on: :collection
    end
    resources :users, only: [:show, :create, :update, :destroy]
    resources :tags, only: [:index, :destroy]
    root to: "articles#index"
  end

  match "/sitemap" => "sitemap#index", as: :sitemap, defaults: {format: :xml}

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :title, :tag_names, :user_id, :published_on, :markdown, :use_editor, :draft

  validates_presence_of :title

  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :images, class_name: "ArticleImage", dependent: :destroy
  has_many :impressions, as: :impressionable
  belongs_to :user
  scope :published, -> { where(draft: false) }
  scope :drafts, -> { where(draft: true) }

  validates_numericality_of :user_id
  default_scope order: 'published_on DESC'

  attr_writer :tag_names
  after_save :assign_tags

  def tag_names
    @tag_names || tags.map(&:name).join(", ")
  end

  def self.search(search)
    if search
      ActionController::Base.new.expire_fragment('all_articles')
      where('title LIKE ?', "%#{search}%")
    else
      published
    end
  end

  def impression_count
    impressions.size
  end

  def unique_impression_count
    impressions.group(:ip_address).size #UNTESTED: might not be correct syntax
  end

  private

  def assign_tags
    if @tag_names
      ActionController::Base.new.expire_fragment('shared_tags')
      ActionController::Base.new.expire_fragment('all_articles')
      self.tags = @tag_names.split(",").map do |name|
        Tag.find_or_create_by_name(name.strip)
      end
    end
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  load_and_authorize_resource :article, except: [:index, :create, :new]
  before_filter :authenticate_user!, except: [:index, :show]

  layout 'admin'

  def index
    authorize! :access, :admin
    @articles = Article.published.all(include: :user)
    @drafts = Article.drafts.all
    @tags = Tag.all
    @users = User.all
  end

  def show
    authorize! :access, :admin
    respond_to do |format|
      format.html
      format.json { render json: @article }
    end
  end

  def new
    @article = Article.new
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @article }
    end
  end

  def edit
  end

  def create
    @article = Article.new(params[:article])
    authorize! :create, @article
    @article.user_id = current_user.id
    respond_to do |format|
      if @article.save
        expire_fragment "recent_posts"
        expire_fragment "all_articles"
        format.html { redirect_to admin_articles_path, notice: 'Article was successfully created.' }
        format.js
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update_attributes(params[:article])
        expire_fragment "recent_posts"
        expire_fragment "all_articles"
        format.html { redirect_to admin_articles_path, notice: 'Article was successfully updated.' }
        format.json { render json: @article, status: :ok, location: @article}
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    expire_fragment "recent_posts"
    expire_fragment "all_articles"
    respond_to do |format|
      format.html { redirect_to admin_articles_path }
      format.js
      format.json { head :no_content }
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ActionView::Helpers::TextHelper

  load_and_authorize_resource :article, except: [:index, :create, :new]
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :log_impression, only: [:show]
  layout "public"

  def index
    @articles = Article.search(params[:search]).paginate(per_page: 4, page: params[:page])
    @articles_by_date = @articles.group_by(&:published_on)
    @for_slideshow = []

    Article.published.each do |article|
      if article.images.main.first.present?
        @for_slideshow << article
      end
    end
    @date = params[:date] ? Date.parse(params[:date]) : Date.today

    if request.xhr?
      render partial: "articles/articles", locals: {articles: @articles}
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  def log_impression
    @article.impressions.create(ip_address: request.remote_ip, user_id: @article.user.id)
  end

  protected

  def set_ariane
    super
    if params[:id].present?
      article = Article.find(params[:id])
      ariane.add truncate(article.title, length: 30 ), article_path(article)
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def output_content_for(article)
    if article.body.present?
      return truncate(article.body, length: 250).html_safe
    elsif article.markdown.present?
      return markdown truncate(article.markdown, length: 250)
    end
  end

  def output_detailed_content_for(article)
    if article.body.present?
      return article.body.html_safe
    elsif article.markdown.present?
      return markdown article.markdown
    end
  end
end

app/views/admin/articles/_article.html.erb
<li>
	<article id="article_<%=article.id%>">
	  <div id="article-content">
	    <div class="title">
	      <h4><%= article.title %></h4>
	    </div>
	    <span><%= t(:'.viewed') %><%= article.impression_count%></span>
	  </div>
	  <%= link_to t(:'common.edit'), edit_admin_article_path(article) %> |
	  <%= link_to t(:'common.delete'), admin_article_path(article), confirm: t(:'.confirm_delete'), remote: true, method: :delete %>
  </article>
</li>

app/views/admin/articles/_comment.html.erb
<li class="comment">
  <div class = "comment-author">
    <%= comment.name %>
    <time><%= comment.created_at %></time>
    <%= link_to t(:'common.delete'), admin_article_comment_path(@article, comment),
                confirm: t(:'.confirm_delete'),
                method: :delete %>
  </div>
  <div class="comment-body">
    <%= simple_format comment.body %>
  </div>
</li>

app/views/admin/articles/_draft.html.erb
<li>
  <article id="article_<%=draft.id%>">
    <div id="article-content">
      <div class="title">
        <h4><%= draft.title %></h4>
        <%= simple_format draft.body %>
      </div>
    </div>
    <%= link_to t(:'common.edit'), edit_admin_article_path(draft) %> |
    <%= link_to t(:'common.delete'), admin_article_path(draft), confirm: t(:'.confirm_delete'), remote: true, method: :delete %>
  </article>
</li>

app/views/admin/articles/_form.html.erb
<% draft ||= false %>
<% @article.persisted? ? remote = {remote: false} : remote = {remote: true} %>
<%= simple_form_for([:admin, @article], remote ) do |f| %>
  <%= f.input :draft, as: 'hidden', input_html: { value: false } %>
  <%= f.input :title %>
  <% unless @article.persisted? %>
    <div class="controls">
      <ul class="unstyled horizontal-list">
        <li>
          <label class="radio">
            <input type="radio" value="true" name="article[use_editor]" id="article_use_editor_true" class="radio_buttons optional" checked='checked'>Use editor
          </label>
        </li>
        <li>
          <label class="radio">
            <input type="radio" value="false" name="article[use_editor]" id="article_use_editor_false" class="radio_buttons optional">Use Markdown
          </label>
        </li>
      </ul>
    </div>
  <% end %>
  <%= f.input :body, as: 'text', input_html: {class: 'wysihtml5'}  unless @article.persisted? && !@article.use_editor %>

  <% unless @article.persisted? && @article.use_editor %>
    <div class="control-group text optional <%= 'hidden' unless @article.persisted? && !@article.use_editor %>">
      <label for="article_markdown" class="text optional control-label">Markdown</label>
      <div class="controls">
        <%= f.text_area :markdown %>
      </div>
    </div>
  <% end %>
  <%= f.input :tag_names, input_html: { autocomplete: "off", class: "typeahead", data: {provide: "typeahead", source: Tag.all.map(&:name)} } %>
  <%= f.input :published_on, as: 'string' %>
  <%= f.button :submit, class: "btn-primary" %>
  <% unless @article.persisted? %>
    <button id="save-draft" type="button" class="btn"><%= t(:'.save_draft') %></a>
  <% end %>
<% end %>
<% if @article.persisted? %>
  <h2><%= t(:'.images') %></h2>
  <ul id="article-images" class="article-images horizontal-list">
    <% @article.images.each do |image| %>
      <%= render partial: "admin/article_images/article_image", locals: {image: image} %>
    <% end %>
  </ul>
  <%= simple_form_for([:admin, @article, @article.images.build]) do |f| %>
    <%= f.input :image, as: :file, input_html: {multiple: true, name: "article_image[image]"} %>
  <% end %>
<% end %>

app/views/admin/articles/create.js.erb
$('#new_article').remove();
$('#create-article').show();
$('#articles').prepend('<%= j render partial: "admin/articles/article", locals: {article: @article} %>');

app/views/admin/articles/destroy.js.erb
$("#article_<%=@article.id%>").fadeOut();

app/views/admin/articles/edit.html.erb
<h1><%= @article.draft? ? t(:'.create_from_draft') : t(:'.title') %></h1>
<%= render 'form' %>
<%= link_to t(:'common.back'), admin_articles_path %>

app/views/admin/articles/index.html.erb
<ul id="admin-tabs" class="nav nav-tabs">
  <li class="active"><a href="#articles-tab" data-toggle="tab"><%= t(:'.articles') %></a></li>
  <li><a href="#drafts-tab" data-toggle="tab"><%= t(:'.drafts') %></a></li>
  <li><a href="#tags-tab" data-toggle="tab"><%= t(:'.tags') %></a></li>
  <% if can? :access, :admin %>
    <li><a href="#users-tab" data-toggle="tab"><%= t(:'.users') %></a></li>
  <% end %>
</ul>
<div class="tab-content">
  <div class="tab-pane active" id="articles-tab">
    <%= render partial: "admin/articles/tabs/article_tab", locals: {articles: @articles} %>
  </div>
  <div class="tab-pane" id="drafts-tab">
    <%= render partial: "admin/articles/tabs/drafts_tab", locals: {drafts: @drafts} %>
  </div>
  <div class="tab-pane" id="tags-tab">
    <%= render partial: "admin/articles/tabs/tags_tab", locals: {tags: @tags} %>
  </div>
  <% if can? :access, :admin %>
  <div class="tab-pane" id="users-tab">
    <%= render partial: "admin/articles/tabs/users_tab", locals: {users: @users} %>
  </div>
  <% end %>
</div>

app/views/admin/articles/new.html.erb
 <h1><%= t(:'.title') %></h1>

<%= render 'form' %>

<%= link_to t(:'common.back'), admin_articles_path %>

app/views/admin/articles/new.js.erb
$('#create-article').hide().after('<%= j render("form") %>');
$('#article_published_on').datepicker({dateFormat: 'yy-mm-dd'});
$('#article_body').wysihtml5();

app/views/admin/articles/show.html.erb
<%= render partial: 'article', locals: { article: @article, with_comments: true }%>
<%= link_to t(:'common.back'), admin_articles_path %>