config/routes.rb
Blog::Application.routes.draw do

  get "sitemap/index"

  devise_for :users, {controllers: {omniauth_callbacks: "omniauth_callbacks"}}

  root to: "articles#index"

  resources :users, only: [:show, :index, :update]

  resources :articles, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :tags, only: [:show]

  namespace :admin do
    resources :articles do
      resources :article_images, only: [:create, :update, :destroy]
      get :drafts, on: :collection
    end
    resources :users, only: [:show, :create, :update, :destroy]
    resources :tags, only: [:index, :destroy]
    root to: "articles#index"
  end

  match "/sitemap" => "sitemap#index", as: :sitemap, defaults: {format: :xml}

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :title, :tag_names, :user_id, :published_on, :markdown, :use_editor, :draft

  validates_presence_of :title

  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :images, class_name: "ArticleImage", dependent: :destroy
  has_many :impressions, as: :impressionable
  belongs_to :user
  scope :published, -> { where(draft: false) }
  scope :drafts, -> { where(draft: true) }

  validates_numericality_of :user_id
  default_scope order: 'published_on DESC'

  attr_writer :tag_names
  after_save :assign_tags

  def tag_names
    @tag_names || tags.map(&:name).join(", ")
  end

  def self.search(search)
    if search
      ActionController::Base.new.expire_fragment('all_articles')
      where('title LIKE ?', "%#{search}%")
    else
      published
    end
  end

  def impression_count
    impressions.size
  end

  def unique_impression_count
    impressions.group(:ip_address).size #UNTESTED: might not be correct syntax
  end

  private

  def assign_tags
    if @tag_names
      ActionController::Base.new.expire_fragment('shared_tags')
      ActionController::Base.new.expire_fragment('all_articles')
      self.tags = @tag_names.split(",").map do |name|
        Tag.find_or_create_by_name(name.strip)
      end
    end
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  load_and_authorize_resource :article, except: [:index, :create, :new]
  before_filter :authenticate_user!, except: [:index, :show]

  layout 'admin'

  def index
    authorize! :access, :admin
    @articles = Article.published.all(include: :user)
    @drafts = Article.drafts.all
    @tags = Tag.all
    @users = User.all
  end

  def show
    authorize! :access, :admin
    respond_to do |format|
      format.html
      format.json { render json: @article }
    end
  end

  def new
    @article = Article.new
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @article }
    end
  end

  def edit
  end

  def create
    @article = Article.new(params[:article])
    authorize! :create, @article
    @article.user_id = current_user.id
    respond_to do |format|
      if @article.save
        expire_fragment "recent_posts"
        expire_fragment "all_articles"
        format.html { redirect_to admin_articles_path, notice: 'Article was successfully created.' }
        format.js
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update_attributes(params[:article])
        expire_fragment "recent_posts"
        expire_fragment "all_articles"
        format.html { redirect_to admin_articles_path, notice: 'Article was successfully updated.' }
        format.json { render json: @article, status: :ok, location: @article}
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    expire_fragment "recent_posts"
    expire_fragment "all_articles"
    respond_to do |format|
      format.html { redirect_to admin_articles_path }
      format.js
      format.json { head :no_content }
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ActionView::Helpers::TextHelper

  load_and_authorize_resource :article, except: [:index, :create, :new]
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :log_impression, only: [:show]
  layout "public"

  def index
    @articles = Article.search(params[:search]).paginate(per_page: 4, page: params[:page])
    @articles_by_date = @articles.group_by(&:published_on)
    @for_slideshow = []

    Article.published.each do |article|
      if article.images.main.first.present?
        @for_slideshow << article
      end
    end
    @date = params[:date] ? Date.parse(params[:date]) : Date.today

    if request.xhr?
      render partial: "articles/articles", locals: {articles: @articles}
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  def log_impression
    @article.impressions.create(ip_address: request.remote_ip, user_id: @article.user.id)
  end

  protected

  def set_ariane
    super
    if params[:id].present?
      article = Article.find(params[:id])
      ariane.add truncate(article.title, length: 30 ), article_path(article)
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def output_content_for(article)
    if article.body.present?
      return truncate(article.body, length: 250).html_safe
    elsif article.markdown.present?
      return markdown truncate(article.markdown, length: 250)
    end
  end

  def output_detailed_content_for(article)
    if article.body.present?
      return article.body.html_safe
    elsif article.markdown.present?
      return markdown article.markdown
    end
  end
end

app/views/articles/_article.html.erb
<article>
  <div class="row">
    <% main_image = article.images.main.first %>
    <% if main_image.present? %>
    <div class="span3">
      <%= image_tag main_image.image_url(:thumb) %>
    </div>
    <div class="span6">
    <% else %>
    <div class="span8">
    <% end %>
      <section>
        <header>
          <h2><%= article.title %></h2>
          <p>
            <%= t(:'.tags') %>
            <% article.tags.each do |tag|%>
              <%= link_to tag.name, tag_path(tag) %><%= ',' unless tag == article.tags.last %>
            <% end %>
          </p>
        </header>
        <div class="content">
          <%= output_content_for(article) %>
        </div>
        <footer>
          <%= link_to t(:'.full_article'), article_path(article), class: "btn btn-primary" %>
        </footer>
      </section>
    </div>
  </div>
</article>

app/views/articles/_articles.html.erb
  <%= link_to t(:'common.all_articles'), articles_path, id: "main-back" unless params[:search].blank? %>
  <% if articles.empty? %>
    <div class="fallback"><%= t(:'.no_articles_found', query: params[:search]) %></div>
  <% end %>

  <ul id="articles" class="unstyled">
    <% articles.each do |article| %>
      <% if articles.empty? %>
        <li><%= t(:'shared.no_recent_posts') %></li>
      <% end %>
      <li>
        <%= render partial: "articles/article", locals: { article: article } %>
      </li>
      <hr>
    <% end %>
  </ul>
  <%= will_paginate articles %>

app/views/articles/_comment.html.erb
<li class="comment">
  <div class="comment-author">
    <%= comment.name %> (<%= mail_to comment.email %>)
    <time><%= l comment.created_at, format: :blog_short_time %></time>
  </div>
  <div class="comment-body">
    <%= simple_format comment.body %>
  </div>
</li>

app/views/articles/_detailed_article.html.erb
<% present article do |article_presenter| %>
  <% cache article do %>
    <article class="detailed">
      <div class="row">
        <% if article_presenter.image.present? %>
        <div class="span8 large-image">
          <%= article_presenter.image %>
        </div>
        <div class="span8">
        <% else %>
        <div class="span8">
        <% end %>
          <section>
            <header>
              <h2><%= article_presenter.title %></h2>
              <p>
                <%= t(:'.tags') %>
                <% article_presenter.tags %>
              </p>
            </header>
            <div class="row">
              <div class="span7">
                <div>
                  <%= output_detailed_content_for(article) %>
                </div>
              </div>
            </div>
            <% if article.images.inline.present? %>
              <hr>
              <div class="row">
                <div class="images span6">
                  <h3><%= t(:'.gallery') %></h3>
                  <%= article_presenter.inline_images %>
                </div>
              </div>
            <% end %>
            <footer>
              <p><%= t(:'articles.article.by') %> <%= link_to article.user.name, user_path(article.user) %>
                <%= t(:'articles.article.on_date') %> <time><%= article_presenter.published_on %></time>
              </p>
            </footer>
          </section>
          <hr>
          <section id="comment-section">
            <h3><%= t(:'articles.article.comments') %></h3>
            <% unless  article.comments.empty? %>
              <ul id="comments" class="unstyled">
                <% article.comments.each do |comment| %>
                  <%= render partial: "articles/comment", locals: { comment: comment }%>
                <% end %>
              </ul>
            <% end %>
            <a href="" class="btn comment-on-article"><%= t(:'.comment') %></a>
            <%= simple_form_for([article, article.comments.build]) do |f| %>
              <%= f.input :name %>
              <%= f.input :email%>
              <%= f.input :body, as: 'text'%>
              <%= f.button :submit %>
            <% end %>
          </section>
          <hr>
        </div>
      </div>
    </article>
  <% end %>
<% end %>

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.input :title %>
  <%= f.input :body, as: 'text' %>
  <%= f.input :tag_names %>
  <%= f.input :published %>
  <%= f.button :submit%>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% content_for :head, auto_discovery_link_tag(:rss, articles_url(format: "rss")) %>
<ul id="nav-tabs" class="nav nav-tabs">

  <li class="active">
    <a id="articles-tab" href="#article-section" data-toggle="tab"><%= t(:'.list_articles') %></a>
  </li>
  <li>
    <a id="slideshow-tab" href="#slideshow-section" data-toggle="tab"><%= t(:'.slideshow') %></a>
  </li>  <li>
    <a id="calendar-tab" href="#calendar-section" data-toggle="tab"><%= t(:'.calendar') %></a>
  </li>
  <li class="rss-icon">
    <%= link_to image_tag("icons/feed-icon-28x28.png"), articles_url(format: "rss") %>
  </li>
</ul>

<div class="tab-content">
  <section id="article-section" class="tab-pane active">
    <% if @articles.blank? %>
      <p class="fallback"><%= t(:'.fallback_no_articles') %></p>
    <% else %>
      <% cache "all_articles" do %>
      <%= render partial: "articles", locals: {articles: @articles} %>
      <% end %>
    <% end %>
  </section>
  <section id="slideshow-section" class="tab-pane">
    <div class="row">
      <div id="slideshow" class="carousel slide span8" data-inteval="50000" data-pause="hover">
        <!-- Carousel items -->
        <div class="carousel-inner">
          <% @for_slideshow.each do |article| %>
            <div class="item <%= "active" if article == @for_slideshow.first %>">
              <%= image_tag article.images.main.first.image_url(:large) %>
              <div class="carousel-caption">
                <h4><a href="<%= article_path(article) %>" class="element-link"><%= article.title %><span></span></a></h4>
                <div class="content">
                  <%= output_content_for(article) %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <!-- Carousel nav -->
        <a class="carousel-control left" href="#slideshow" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#slideshow" data-slide="next">&rsaquo;</a>
      </div>
    </div>
  </section>
  <section id="calendar-section" class="tab-pane">
    <h2 id="month">
      <%= link_to "<", date: @date.prev_month %>
      <%= @date.strftime("%B %Y") %>
      <%= link_to ">", date: @date.next_month %>
    </h2>
    <%= calendar @date do |date| %>
      <%= date.day %>
      <% if @articles_by_date[date] %>
        <% puts @articles_by_date[date] %>
        <ul>
          <% @articles_by_date[date].each do |article| %>
            <li><%= link_to truncate(article.title, length: 18), article_path(article), title: article.title %></li>
          <% end %>
        </ul>
      <% end %>
    <% end %>
    <hr>
  </section>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= render partial: 'detailed_article', locals: { article: @article }%>