config/routes.rb
Blog::Application.routes.draw do

  get "sitemap/index"

  devise_for :users, {controllers: {omniauth_callbacks: "omniauth_callbacks"}}

  root to: "articles#index"

  resources :users, only: [:show, :index, :update]

  resources :articles, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :tags, only: [:show]

  namespace :admin do
    resources :articles do
      resources :article_images, only: [:create, :update, :destroy]
      get :drafts, on: :collection
    end
    resources :users, only: [:show, :create, :update, :destroy]
    resources :tags, only: [:index, :destroy]
    root to: "articles#index"
  end

  match "/sitemap" => "sitemap#index", as: :sitemap, defaults: {format: :xml}

end

app/views/shared/_login_modal.html.erb
<div id="login-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="login-modal-label"><%= t(:'layouts.application.title') %></h3>
  </div>
  <div class="modal-body">
    <%= render partial: "devise/sessions/form", locals: {resource: User.new, modal: true}%>
  </div>
  <div class="modal-footer">
    <%= link_to "", user_omniauth_authorize_path(:twitter),
        class: "sign-in-icon twitter",
        title: t(:'layouts.navigation.sign_in_twitter') %>
        <%= link_to "", user_omniauth_authorize_path(:facebook),
        class: "sign-in-icon facebook",
        title: t(:'layouts.navigation.sign_in_facebook') %>


    <button class="btn btn-primary" type="submit"><%= t(:'layouts.navigation.log_in') %></button>
    <a class="btn" type="submit" href="<%= new_registration_path(resource_name) %>">
      <%= t(:'layouts.navigation.sign_up') %>
    </a>
  </div>
</div>

app/views/shared/_profile.html.erb
<section id="profile">
  <div>
    <%= avatar(user, 'small') %>
    <p><%= user.first_name %> <%= user.last_name %></p>
  </div>
  <%= link_to t(:'.profile_link'),  user_path(user) %>
</section>
<hr>

app/views/shared/_recent_posts.html.erb
<% cache "recent_posts" do %>
  <section id="recent posts">
    <h3><%= t(:'shared.recent_posts') %></h3>
    <ul class="recent-posts unstyled">
      <% articles = Article.all %>
      <% if articles.empty? %>
        <li><%= t(:'shared.no_recent_posts') %></li>
      <% end %>
      <% Article.all(limit: 3).each do |article| %>
        <li>
          <%= image_tag article.images.main.first.image_url(:small) unless article.images.main.first.blank? %>
          <h4 class="<%= 'with-image' unless article.images.main.first.blank? %>">
            <%= link_to article.title, article_path(article) %>
          </h4>
        </li>
      <% end %>
    </ul>
  </section>
  <hr>
<% end %>

app/views/shared/_sign_up_modal.html.erb
<div id="sign-up-modal" class="login-modal modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 class="login-modal-label"><%= t(:'shared.sign_up_modal_header') %></h3>
  </div>
  <div class="modal-body">
    <%= render partial: "devise/registrations/form", locals: {resource: User.new, modal: true} %>
  </div>
  <div class="modal-footer">
    <%= link_to "", user_omniauth_authorize_path(:twitter),
        class: "sign-in-icon sprites-twitter",
        title: t(:'layouts.navigation.sign_in_twitter') %>
        <%= link_to "", user_omniauth_authorize_path(:facebook),
        class: "sign-in-icon sprites-facebook",
        title: t(:'layouts.navigation.sign_in_facebook') %>

    <button class="btn btn-primary" type="submit"><%= t(:'layouts.navigation.sign_up') %></button>
  </div>
</div>

app/views/shared/_tags.html.erb
<% cache 'shared_tags' do%>
  <section id="tags">
    <h3><%= t(:'.title') %></h3>
    <ul id= "tags" class="unstyled horizontal-list">
      <% tags = Tag.all %>
      <% tags.each do |tag| %>
        <li>
          <%= link_to tag.name, tag_path(tag) %><% unless tag == tags.last %>,<% end %>
        </li>
      <% end %>
    </ul>
  </section>
<% end %>