config/routes.rb
Blog::Application.routes.draw do

  get "sitemap/index"

  devise_for :users, {controllers: {omniauth_callbacks: "omniauth_callbacks"}}

  root to: "articles#index"

  resources :users, only: [:show, :index, :update]

  resources :articles, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :tags, only: [:show]

  namespace :admin do
    resources :articles do
      resources :article_images, only: [:create, :update, :destroy]
      get :drafts, on: :collection
    end
    resources :users, only: [:show, :create, :update, :destroy]
    resources :tags, only: [:index, :destroy]
    root to: "articles#index"
  end

  match "/sitemap" => "sitemap#index", as: :sitemap, defaults: {format: :xml}

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :title, :tag_names, :user_id, :published_on, :markdown, :use_editor, :draft

  validates_presence_of :title

  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :images, class_name: "ArticleImage", dependent: :destroy
  has_many :impressions, as: :impressionable
  belongs_to :user
  scope :published, -> { where(draft: false) }
  scope :drafts, -> { where(draft: true) }

  validates_numericality_of :user_id
  default_scope order: 'published_on DESC'

  attr_writer :tag_names
  after_save :assign_tags

  def tag_names
    @tag_names || tags.map(&:name).join(", ")
  end

  def self.search(search)
    if search
      ActionController::Base.new.expire_fragment('all_articles')
      where('title LIKE ?', "%#{search}%")
    else
      published
    end
  end

  def impression_count
    impressions.size
  end

  def unique_impression_count
    impressions.group(:ip_address).size #UNTESTED: might not be correct syntax
  end

  private

  def assign_tags
    if @tag_names
      ActionController::Base.new.expire_fragment('shared_tags')
      ActionController::Base.new.expire_fragment('all_articles')
      self.tags = @tag_names.split(",").map do |name|
        Tag.find_or_create_by_name(name.strip)
      end
    end
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  load_and_authorize_resource :article, except: [:index, :create, :new]
  before_filter :authenticate_user!, except: [:index, :show]

  layout 'admin'

  def index
    authorize! :access, :admin
    @articles = Article.published.all(include: :user)
    @drafts = Article.drafts.all
    @tags = Tag.all
    @users = User.all
  end

  def show
    authorize! :access, :admin
    respond_to do |format|
      format.html
      format.json { render json: @article }
    end
  end

  def new
    @article = Article.new
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @article }
    end
  end

  def edit
  end

  def create
    @article = Article.new(params[:article])
    authorize! :create, @article
    @article.user_id = current_user.id
    respond_to do |format|
      if @article.save
        expire_fragment "recent_posts"
        expire_fragment "all_articles"
        format.html { redirect_to admin_articles_path, notice: 'Article was successfully created.' }
        format.js
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update_attributes(params[:article])
        expire_fragment "recent_posts"
        expire_fragment "all_articles"
        format.html { redirect_to admin_articles_path, notice: 'Article was successfully updated.' }
        format.json { render json: @article, status: :ok, location: @article}
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    expire_fragment "recent_posts"
    expire_fragment "all_articles"
    respond_to do |format|
      format.html { redirect_to admin_articles_path }
      format.js
      format.json { head :no_content }
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ActionView::Helpers::TextHelper

  load_and_authorize_resource :article, except: [:index, :create, :new]
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :log_impression, only: [:show]
  layout "public"

  def index
    @articles = Article.search(params[:search]).paginate(per_page: 4, page: params[:page])
    @articles_by_date = @articles.group_by(&:published_on)
    @for_slideshow = []

    Article.published.each do |article|
      if article.images.main.first.present?
        @for_slideshow << article
      end
    end
    @date = params[:date] ? Date.parse(params[:date]) : Date.today

    if request.xhr?
      render partial: "articles/articles", locals: {articles: @articles}
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  def log_impression
    @article.impressions.create(ip_address: request.remote_ip, user_id: @article.user.id)
  end

  protected

  def set_ariane
    super
    if params[:id].present?
      article = Article.find(params[:id])
      ariane.add truncate(article.title, length: 30 ), article_path(article)
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def output_content_for(article)
    if article.body.present?
      return truncate(article.body, length: 250).html_safe
    elsif article.markdown.present?
      return markdown truncate(article.markdown, length: 250)
    end
  end

  def output_detailed_content_for(article)
    if article.body.present?
      return article.body.html_safe
    elsif article.markdown.present?
      return markdown article.markdown
    end
  end
end

app/views/admin/articles/tabs/_article_tab.html.erb
<h2><%= t(:'.title') %></h2>
<p><%= link_to(t(:'.add_article'), new_admin_article_path, id: "create-article", class: "btn", remote: true) if can? :create, Article %></p>
<hr>
<h3 id="all-articles"><%= t(:'.all_articles') %></h3>
<ul id="articles" class="unstyled">
  <% articles.each do |article| %>
    <% if articles.empty? %>
      <li><%= t(:'shared.no_recent_posts') %></li>
    <% end %>
    <%= render partial: "article", locals: { article: article, with_comments: false } %>
  <% end %>
</ul>

app/views/admin/articles/tabs/_drafts_tab.html.erb
<h3 id="all-articles"><%= t(:'.all_drafts') %></h3>
<ul id="articles" class="unstyled">
  <% if drafts.empty? %>
    <li><%= t(:'.no_drafts') %></li>
  <% else %>
    <% drafts.each do |draft| %>
      <%= render partial: "admin/articles/draft", locals: { draft: draft } %>
    <% end %>
  <% end %>
</ul>

app/views/admin/articles/tabs/_tags_tab.html.erb
<ul id="tags">
  <% tags.each do |tag| %>
    <li>
      <%= tag.name %>
      <%= button_to t(:'common.delete'), admin_tag_path(tag),
        confirm: t(:'shared.tags.confirm_delete'), method: :delete
      %>
    </li>
  <% end %>
</ul>

app/views/admin/articles/tabs/_users_tab.html.erb
<h2><%= t(:'.title') %></h2>
<div>
  <button type="button" class="btn" id="create-user"><%= t(:'.add_user') %></button>
</div>

<%= simple_form_for([:admin, User.new], html: {id: "admin-new-user"}) do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email, required: true%>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.input :avatar, as: 'file' %>
  <%= f.input :role, collection: User::ROLES, prompt: t(:'.select_role') %>
  <%= f.button :submit, class: "btn btn-primary"%>
<% end %>

<hr>
<h3 id="all-users"><%= t(:'.all_users') %></h3>
<div class="accordion" id="user-accordion">
  <% users.each do |user| %>
    <div class="accordion-group">
      <div class="accordion-heading" data-url="<%= admin_user_path(user) %>">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#user-accordion" href="#user-<%= user.id %>-collapse">
          <%= render partial: "admin/users/full_name", locals: {user: user} %>
        </a>
      </div>
      <div id="user-<%= user.id %>-collapse" class="accordion-body collapse">
	      <div class="accordion-inner">
	      	<%= image_tag user.avatar.url(:small)%>
          <p class="edit-in-place">
					  <b><%= t(:'.first_name') %></b>
					  <%= best_in_place user, :first_name, path: admin_user_path(user) %>
            <i class="icon-edit"></i>
					</p>
          <p class="edit-in-place">
					  <b><%= t(:'.last_name') %></b>
					  <%= best_in_place user, :last_name, path: admin_user_path(user) %>
            <i class="icon-edit"></i>
					</p>
          <p class="edit-in-place">
					  <b><%= t(:'.username') %></b>
					  <%= best_in_place user, :username, path: admin_user_path(user) %>
            <i class="icon-edit"></i>
					</p>
          <p class="edit-in-place">
            <b><%= t(:'.password') %></b>
            <%= best_in_place user, :password, path: admin_user_path(user) %>
            <i class="icon-edit"></i>
          </p>
          <p class="edit-in-place">
					  <b><%= t(:'.email') %></b>
					  <%= best_in_place user, :email, path: admin_user_path(user) %>
            <i class="icon-edit"></i>
					</p>
      	</div>
      </div>
    </div>
  <% end %>
</div>